{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# [Error Handling](https://docs.pydantic.dev/latest/errors/errors/)\n",
    "\n",
    "Pydantic 은 검증 중인 데이터에서 오류를 발견할 때마다 `ValidationError` 를 발생시킵니다.\n",
    "\n",
    "> [!NOTE]\n",
    "> 유효성 검사 코드는 `ValidationError` 자체를 발생시켜서는 안되며, ValidationError를 채우는 데 사용되는 `ValueError` 또는 `AssertionError`(또는 그 하위 클래스)를 발생시켜야 합니다.\n",
    "\n",
    "발견된 오류 수에 관계없이 한 가지 예외가 발생합니다. `ValidationError` 에는 모든 오류와 오류 발생 방식에 대한 정보가 포함됩니다.\n",
    "\n",
    "여러 가지 방법으로 이러한 오류에 액세스할 수 있습니다:\n",
    "\n",
    "| Method            | Description                                    |\n",
    "| ----------------- | ---------------------------------------------- |\n",
    "| `e.errors()`      | 입력 데이터에서 발견된 오류 목록을 반환합니다. |\n",
    "| `e.error_count()` | 오류에서 발견된 오류 수를 반환합니다.          |\n",
    "| `e.json()`        | 오류에 대한 JSON 표현을 반환합니다.            |\n",
    "| `str(e)`          | 사람이 읽을 수 있는 오류 표현을 반환합니다.    |\n",
    "\n",
    "각 오류 개체에는 다음이 포함됩니다:\n",
    "\n",
    "| Property | Description                                                       |\n",
    "| -------- | ----------------------------------------------------------------- |\n",
    "| `ctx`    | 오류 메시지를 렌더링하는 데 필요한 값이 포함된 선택적 개체입니다. |\n",
    "| `input`  | 유효성 검사를 위해 제공된 입력입니다.                             |\n",
    "| `loc`    | 오류 위치를 목록으로 표시합니다.                                  |\n",
    "| `msg`    | 사람이 읽을 수 있는 오류 설명입니다.                              |\n",
    "| `type`   | 컴퓨터에서 읽을 수 있는 오류 유형 식별자입니다.                   |\n",
    "| `url`    | 오류에 대한 추가 정보에 대한 URL입니다.                           |\n",
    "\n",
    "`loc` 목록의 첫 번째 항목은 오류가 발생한 필드가 되며, 해당 필드가 하위 모델인 경우 후속 항목이 나타나 오류의 중첩 위치를 나타냅니다.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import List\n",
    "\n",
    "from pydantic import BaseModel, ValidationError, conint\n",
    "\n",
    "\n",
    "class Location(BaseModel):\n",
    "    lat: float = 0.1\n",
    "    lng: float = 10.1\n",
    "\n",
    "\n",
    "class Model(BaseModel):\n",
    "    is_required: float\n",
    "    gt_int: conint(gt=42)\n",
    "    list_of_ints: List[int] = None\n",
    "    a_float: float = None\n",
    "    recursive_model: Location = None\n",
    "\n",
    "\n",
    "data = dict(\n",
    "    list_of_ints=[\"1\", 2, \"bad\"],\n",
    "    a_float=\"not a float\",\n",
    "    recursive_model={\"lat\": 4.2, \"lng\": \"New York\"},\n",
    "    gt_int=21,\n",
    ")\n",
    "\n",
    "try:\n",
    "    Model(**data)\n",
    "except ValidationError as e:\n",
    "    print(e)\n",
    "\n",
    "try:\n",
    "    Model(**data)\n",
    "except ValidationError as e:\n",
    "    print(e.errors())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```bash\n",
    "5 validation errors for Model\n",
    "is_required\n",
    "  Field required [type=missing, input_value={'list_of_ints': ['1', 2,...ew York'}, 'gt_int': 21}, input_type=dict]\n",
    "    For further information visit https://errors.pydantic.dev/2.8/v/missing\n",
    "gt_int\n",
    "  Input should be greater than 42 [type=greater_than, input_value=21, input_type=int]\n",
    "    For further information visit https://errors.pydantic.dev/2.8/v/greater_than\n",
    "list_of_ints.2\n",
    "  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='bad', input_type=str]\n",
    "    For further information visit https://errors.pydantic.dev/2.8/v/int_parsing\n",
    "a_float\n",
    "  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='not a float', input_type=str]\n",
    "    For further information visit https://errors.pydantic.dev/2.8/v/float_parsing\n",
    "recursive_model.lng\n",
    "  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='New York', input_type=str]\n",
    "    For further information visit https://errors.pydantic.dev/2.8/v/float_parsing\n",
    "```\n",
    "\n",
    "```python\n",
    "[\n",
    "    {\n",
    "        \"type\": \"missing\",\n",
    "        \"loc\": (\"is_required\",),\n",
    "        \"msg\": \"Field required\",\n",
    "        \"input\": {\n",
    "            \"list_of_ints\": [\"1\", 2, \"bad\"],\n",
    "            \"a_float\": \"not a float\",\n",
    "            \"recursive_model\": {\"lat\": 4.2, \"lng\": \"New York\"},\n",
    "            \"gt_int\": 21,\n",
    "        },\n",
    "        \"url\": \"https://errors.pydantic.dev/2.8/v/missing\",\n",
    "    },\n",
    "    {\n",
    "        \"type\": \"greater_than\",\n",
    "        \"loc\": (\"gt_int\",),\n",
    "        \"msg\": \"Input should be greater than 42\",\n",
    "        \"input\": 21,\n",
    "        \"ctx\": {\"gt\": 42},\n",
    "        \"url\": \"https://errors.pydantic.dev/2.8/v/greater_than\",\n",
    "    },\n",
    "    {\n",
    "        \"type\": \"int_parsing\",\n",
    "        \"loc\": (\"list_of_ints\", 2),\n",
    "        \"msg\": \"Input should be a valid integer, unable to parse string as an integer\",\n",
    "        \"input\": \"bad\",\n",
    "        \"url\": \"https://errors.pydantic.dev/2.8/v/int_parsing\",\n",
    "    },\n",
    "    {\n",
    "        \"type\": \"float_parsing\",\n",
    "        \"loc\": (\"a_float\",),\n",
    "        \"msg\": \"Input should be a valid number, unable to parse string as a number\",\n",
    "        \"input\": \"not a float\",\n",
    "        \"url\": \"https://errors.pydantic.dev/2.8/v/float_parsing\",\n",
    "    },\n",
    "    {\n",
    "        \"type\": \"float_parsing\",\n",
    "        \"loc\": (\"recursive_model\", \"lng\"),\n",
    "        \"msg\": \"Input should be a valid number, unable to parse string as a number\",\n",
    "        \"input\": \"New York\",\n",
    "        \"url\": \"https://errors.pydantic.dev/2.8/v/float_parsing\",\n",
    "    },\n",
    "]\n",
    "```\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Custom Errors\n",
    "\n",
    "사용자 정의 데이터 유형 또는 유효성 검사기에서는 오류를 발생시키려면 `ValueError` 또는 `AssertionError` 를 사용해야 합니다.\n",
    "\n",
    "`@validator` decorator 사용에 대한 자세한 내용은 [Validators](https://docs.pydantic.dev/latest/concepts/validators/)를 참조하세요:\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pydantic import BaseModel, ValidationError, field_validator\n",
    "\n",
    "\n",
    "class Model(BaseModel):\n",
    "    foo: str\n",
    "\n",
    "    @field_validator(\"foo\")\n",
    "    def value_must_equal_bar(cls, v):\n",
    "        if v != \"bar\":\n",
    "            raise ValueError('value must be \"bar\"')\n",
    "\n",
    "        return v\n",
    "\n",
    "\n",
    "try:\n",
    "    Model(foo=\"ber\")\n",
    "except ValidationError as e:\n",
    "    print(e)\n",
    "    print(e.errors())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```bash\n",
    "1 validation error for Model\n",
    "foo\n",
    "    Value error, value must be \"bar\" [type=value_error, input_value='ber', input_type=str]\n",
    "```\n",
    "\n",
    "```python\n",
    "[\n",
    "    {\n",
    "        'type': 'value_error',\n",
    "        'loc': ('foo',),\n",
    "        'msg': 'Value error, value must be \"bar\"',\n",
    "        'input': 'ber',\n",
    "        'ctx': {'error': ValueError('value must be \"bar\"')},\n",
    "        'url': 'https://errors.pydantic.dev/2/v/value_error',\n",
    "    }\n",
    "]\n",
    "```\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "`PydanticCustomError` 를 사용하여 오류 구조를 완전히 제어할 수도 있습니다:\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pydantic_core import PydanticCustomError\n",
    "\n",
    "from pydantic import BaseModel, ValidationError, field_validator\n",
    "\n",
    "\n",
    "class Model(BaseModel):\n",
    "    foo: str\n",
    "\n",
    "    @field_validator(\"foo\")\n",
    "    def value_must_equal_bar(cls, v):\n",
    "        if v != \"bar\":\n",
    "            raise PydanticCustomError(\n",
    "                \"not_a_bar\",\n",
    "                'value is not \"bar\", got \"{wrong_value}\"',\n",
    "                dict(wrong_value=v),\n",
    "            )\n",
    "        return v\n",
    "\n",
    "\n",
    "try:\n",
    "    Model(foo=\"ber\")\n",
    "except ValidationError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```bash\n",
    "1 validation error for Model\n",
    "foo\n",
    "  value is not \"bar\", got \"ber\" [type=not_a_bar, input_value='ber', input_type=str]\n",
    "```\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Error messages\n",
    "\n",
    "Pydantic 은 유효성 검사 및 사용 오류에 대해 유용한 기본 오류 메시지를 제공하려고 시도합니다.\n",
    "\n",
    "다음 섹션에서는 기본 오류 코드에 대한 설명서를 제공했습니다:\n",
    "\n",
    "- [Validation errors](https://docs.pydantic.dev/latest/errors/validation_errors/): 참조 용도로 활용하기.\n",
    "- [Usage errors](https://docs.pydantic.dev/latest/errors/usage_errors/): 참조 용도로 활용하기.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Customize error messages\n",
    "\n",
    "사용자 정의 오류 핸들러를 생성하여 오류 메시지를 사용자 정의할 수 있습니다.\n",
    "\n",
    "일반적인 사용 사례는 오류 메시지를 번역하는 것입니다.\n",
    "예를 들어 아래와 같이 `CUSTOM_MESSAGES` 사전을 번역 사전으로 대체하여 오류 메시지를 번역할 수 있습니다:\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import Dict, List\n",
    "\n",
    "from pydantic_core import ErrorDetails\n",
    "\n",
    "from pydantic import BaseModel, HttpUrl, ValidationError\n",
    "\n",
    "CUSTOM_MESSAGES = {\n",
    "    \"int_parsing\": \"This is not an integer! 🤦\",\n",
    "    \"url_scheme\": \"Hey, use the right URL scheme! I wanted {expected_schemes}.\",\n",
    "}\n",
    "\n",
    "\n",
    "def convert_errors(\n",
    "    e: ValidationError, custom_messages: Dict[str, str]\n",
    ") -> List[ErrorDetails]:\n",
    "    new_errors: List[ErrorDetails] = []\n",
    "    for error in e.errors():\n",
    "        custom_message = custom_messages.get(error[\"type\"])\n",
    "        if custom_message:\n",
    "            ctx = error.get(\"ctx\")\n",
    "            error[\"msg\"] = custom_message.format(**ctx) if ctx else custom_message\n",
    "        new_errors.append(error)\n",
    "    return new_errors\n",
    "\n",
    "\n",
    "class Model(BaseModel):\n",
    "    a: int\n",
    "    b: HttpUrl\n",
    "\n",
    "\n",
    "try:\n",
    "    Model(a=\"wrong\", b=\"ftp://example.com\")\n",
    "except ValidationError as e:\n",
    "    errors = convert_errors(e, CUSTOM_MESSAGES)\n",
    "    print(errors)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```python\n",
    "[\n",
    "    {\n",
    "        \"type\": \"int_parsing\",\n",
    "        \"loc\": (\"a\",),\n",
    "        \"msg\": \"This is not an integer! 🤦\",\n",
    "        \"input\": \"wrong\",\n",
    "        \"url\": \"https://errors.pydantic.dev/2.8/v/int_parsing\",\n",
    "    },\n",
    "    {\n",
    "        \"type\": \"url_scheme\",\n",
    "        \"loc\": (\"b\",),\n",
    "        \"msg\": \"Hey, use the right URL scheme! I wanted 'http' or 'https'.\",\n",
    "        \"input\": \"ftp://example.com\",\n",
    "        \"ctx\": {\"expected_schemes\": \"'http' or 'https'\"},\n",
    "        \"url\": \"https://errors.pydantic.dev/2.8/v/url_scheme\",\n",
    "    },\n",
    "]\n",
    "```\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "또 다른 예는 오류의 `loc` 값이 표시되는 방식을 사용자 정의하는 것입니다:\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import Any, Dict, List, Tuple, Union\n",
    "\n",
    "from pydantic import BaseModel, ValidationError\n",
    "\n",
    "\n",
    "def loc_to_dot_sep(loc: Tuple[Union[str, int], ...]) -> str:\n",
    "    path = \"\"\n",
    "    for i, x in enumerate(loc):\n",
    "        if isinstance(x, str):\n",
    "            if i > 0:\n",
    "                path += \".\"\n",
    "            path += x\n",
    "        elif isinstance(x, int):\n",
    "            path += f\"[{x}]\"\n",
    "        else:\n",
    "            raise TypeError(\"Unexpected type\")\n",
    "    return path\n",
    "\n",
    "\n",
    "def convert_errors(e: ValidationError) -> List[Dict[str, Any]]:\n",
    "    new_errors: List[Dict[str, Any]] = e.errors()\n",
    "    for error in new_errors:\n",
    "        error[\"loc\"] = loc_to_dot_sep(error[\"loc\"])\n",
    "    return new_errors\n",
    "\n",
    "\n",
    "class TestNestedModel(BaseModel):\n",
    "    key: str\n",
    "    value: str\n",
    "\n",
    "\n",
    "class TestModel(BaseModel):\n",
    "    items: List[TestNestedModel]\n",
    "\n",
    "\n",
    "data = {\"items\": [{\"key\": \"foo\", \"value\": \"bar\"}, {\"key\": \"baz\"}]}\n",
    "\n",
    "try:\n",
    "    TestModel.model_validate(data)\n",
    "except ValidationError as e:\n",
    "    print(e.errors())\n",
    "    pretty_errors = convert_errors(e)\n",
    "    print(pretty_errors)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```python\n",
    "[\n",
    "    {\n",
    "        \"type\": \"missing\",\n",
    "        \"loc\": (\"items\", 1, \"value\"),\n",
    "        \"msg\": \"Field required\",\n",
    "        \"input\": {\"key\": \"baz\"},\n",
    "        \"url\": \"https://errors.pydantic.dev/2.8/v/missing\",\n",
    "    }\n",
    "]\n",
    "[\n",
    "    {\n",
    "        \"type\": \"missing\",\n",
    "        \"loc\": \"items[1].value\",\n",
    "        \"msg\": \"Field required\",\n",
    "        \"input\": {\"key\": \"baz\"},\n",
    "        \"url\": \"https://errors.pydantic.dev/2.8/v/missing\",\n",
    "    }\n",
    "]\n",
    "```\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
